### ISSUE TITLE
Mining slider behaviour

### ISSUE THREAD

**Issue by minivio** [KinoKabaret/Kinoit-Quasar-Skeleton#9] opened 2018-02-11 16:05 UTC
- **Chrome & Opera**: You have to click on the position you want for the slider. Click on the handle + drag and drop doesn't work. Which made me think at first it was impossible to change the slider value.
- **Safari**: works as expected (except rate, cfr issue #8 ).
- **Firefox**: never shows (see issue #8 )
- **Smartphone**: Handle doesn't always react. When you finally are able to grab it though, then you can move it okay.

**Comment by nothingismagick** [comment] 2018-02-11 17:58
This needs to be checked against v0.2

**Comment by minivio** [comment] 2018-02-11 19:46
Just checked with v0.2

- **Chrome, Safari, Opera & Smartphone**: Sliders now behave as expected. When you set minimum to zero, though, slider disappears and the Begin Minig button doesn't react ant more. You can't relaunch mining without relaoding the page.
![capture d ecran 2018-02-11 a 20 42 38](https://user-images.githubusercontent.com/23116123/36077513-20973580-0f6c-11e8-8630-2b2cff58e5f6.png)

- **Firefox**: slider works but different behaviour when put to zero (see picture)
![capture d ecran 2018-02-11 a 20 44 50](https://user-images.githubusercontent.com/23116123/36077538-6ea82d24-0f6c-11e8-9f0c-95e4906bfbfa.png)

**Comment by nothingismagick** [comment] 2018-02-13 00:32
Thanks. That's good to know! Except in firefox, that's ALMOST the behaviour I intended. You drop the slider to zero and a bunch of things happen in the background:

``` js
let val = Number(this.minerState.minerThrottle)
Cookies.set('minerThrottle', val) // we set the minerThrottle cookie 
window.miner.setThrottle(1) // this tells the miner to wind all the processes down
window.miner.stop() // then its should stop the mining altogether
this.minerState.running = 0 // inform vue that its not running
this.minerState.hashRate = '0' // update the UI for the correct value (as a string) on next start
this.minerState.buttonLabel = 'MINE' // update the UI for new 
clearInterval(this.interval) // stop our interval from cycling
val = null # we null out the val // lend GC a helping hand
```
The mining action should be available again, but it isn't. That's the issue. I'll fixit and report back.

Why firefox is acting up - I don't know. I think it should be a our policy to only support current versions of browsers, I will make this an issue for the group to talk about. In the meantime, I'll remove all hacky firefox flags - maybe that was the problem. You own this issue, so you'll have to close it when its resolved.

**Comment by nothingismagick** [comment] 2018-02-13 21:55
So it works as intended on dev, but on the webpacked version we seem to be hitting a snag. Not sure exactly where it lies, I'd love it if you could take a look at it.

**Comment by nothingismagick** [comment] 2018-02-14 20:21
We might have to turn off "purifycss" as a rule for our build chain. My feeling is that it doesn't really catch everything important.

**Comment by nothingismagick** [comment] 2018-02-15 01:38
I am closing this because as far as I know, the miner works appropriately now.

**Closed by nothingismagick** 2018-02-15 01:38 UTC
